### ISSUE TITLE
Introduce PQL validation

### ISSUE THREAD

**Issue by frisitano** [paralink-network/paralink-node#12]
Introduce a layer of schema validation to ensure that the PQL request is well formed before parsing it to the PQL parser.  This will allow the app to fail fast if the PQL request is badly formed, reduce the risk of errors from edge cases that haven't been accounted for in downstream code and also allow for centralisation of correctness logic.  e.g. instead of having to perform these checks in multiple places: https://github.com/paralink-network/paralink-node/blob/master/src/pql/parser.py#L63, https://github.com/paralink-network/paralink-node/blob/master/src/pql/pipeline.py#L70, https://github.com/paralink-network/paralink-node/blob/master/src/pql/pipeline.py#L90, https://github.com/frisitano/paralink-node/blob/feature/arbitrary_user_query/src/pql/query_sql.py#L27 etc.

**Comment by jbargu** [comment]
I agree, PQL definition is a JSON and could be easily validate by the custom schema. I suggest using something like `pydantic`, and example of JSON validation can be seen [here](https://pydantic-docs.helpmanual.io/usage/schema/).

**Comment by frisitano** [comment]
In the past I've used the validation functionality of [`marshmallow` ](https://github.com/marshmallow-code/marshmallow).  It looks very similar to `pydantic`.  I'll go with `pydantic` as suggested as it looks specifically tailored to the task at hand, validation, and it's a good opportunity to get my hands dirty with a library I haven't used before 😄  I'll put something together for the weekend.

**Comment by frisitano** [comment]
After doing some further reading on `pydantic` I'm beginning to think that it may not be suitable for PQL validation.  `pydantic` is primarily focused on parsing as opposed to validation. E.g. if an input is of the wrong type then `pydanitc` will cast the input value to the defined type,  you can read more about this [here](https://github.com/samuelcolvin/pydantic/issues/578).  I am concerned that this could result in unintended behaviour downstream.  I would propose that instead we use a library that has strict schema enforcement to avoid this.  As I mentioned I have used [`marshmallow` ](https://marshmallow.readthedocs.io/en/stable/quickstart.html#validation) for this in the past but I'm open to suggestions.  What are your thoughts @jbargu?
