### ISSUE TITLE
Add PostgreSQL network, tracked contracts table

### ISSUE THREAD

**Issue by jbargu** [paralink-network/paralink-node#21]
Currently we read the network data from a JSON object. Appropriate tables should be created in the SQL DB, so it can be modified on the frontend as well as with the CLI. For know we read the chain data from the `chain_config.json` and track the status of the chain through the DB (active/inactive, tracked contracts).

**Comment by frisitano** [comment]
I was taking a look at this.  I was thinking we could leverage [`sqlalchemy_utils.EncryptedType`](https://sqlalchemy-utils.readthedocs.io/en/latest/_modules/sqlalchemy_utils/types/encrypted/encrypted_type.html) for the columns which need to be encrypted.  If the above is considered fit for purpose, then I was wondering if you had any thoughts on how the user would provide the encryption key?

**Comment by jbargu** [comment]
I was also thinking of the best way to provide the key. In the previous version we had a [prompt](https://github.com/paralink-network/paralink-node/blob/ac5a66c97411edef6e17149e12267cb424275dbd/src/network/accounts.py#L68) for the ETH keystore decryption. It had to be entered in both cases: when running `./paralink-node node start` as well as `celery worker collect,execute`. Such key would then persist in the memory, leaving it vulnerable for memory disclosure attacks.

However I assume that the node will be deployed locally in a closed system. In this case a potential attack would be a PQL definition that calls extract (HTTP, SQL) on a local node (either a Paralink node, a running Apache dev server, message broker) or through some other libraries with potential vulnerabilities such as `web3`. To avoid any such shenanigans, we should introduce a blacklist of the URIs that can be called in the PQL, banning localhost loopbacks by default.

The other extreme is also asking for the decryption key every time we need to write it back to the chain. This is of course unfeasible.

Currently I believe the best way would be to provide the key only for the `write` queue worker that writes back to the chain. The whole flow would be: a user would start a paralink-node, open the web interface, login and then click on the `Start event collection` button, which will bring up a prompt for the password. Then the celery workers will be spawned with 3 different queues: `collect`, `execute`, `write` (I would decouple current `execute` task into `execute` and `write`). From all these queues only `write` queue would have access to the private keys (decrypted by the password supplied by the user) - therefore we have to supply the user password when starting this worker (without using message broker). In this way a potentially dangerous PQL definition in `execute` queue will not have any access to the sensitive data. 

To be honest I would not save private keys in the SQL - I know it is in the title, but I put it there to research if this is feasible in any way, but all of my being is against it. I would store it in the JSON encrypted store and then provide IDs that map between the SQL Chain table and the JSON private key for the chain.

**Comment by frisitano** [comment]
Great suggestions on the URI blacklist and decoupling the `execute` and `write` celery tasks.  That will give us the security we need, whilst also being practical.  Thanks for the comprehensive explanation 👍 .
