### ISSUE TITLE
Add React frontend

### ISSUE THREAD

**Issue by jbargu** [paralink-network/paralink-node#22]
Decouple frontend from backend, create a frontend React app and modify the API in the backend with appropriate endpoints. User management should also be taken into the account.

**Comment by ZiyedB** [comment]
Hey,
I'd love to help out on my spare time if you guys needs some extra hands 😄 
Have some good FE experience, and have been very interested lately on crypto.

**Comment by jbargu** [comment]
Hey @ZiyedB, that's great! Right now we are focused on the functionality side of the node, so FE is not getting that much attention. At the moment we would want to bootstrap a React app ([to this empty repo](https://github.com/paralink-network/paralink-ui)) and migrate the existing templates from [here](https://github.com/paralink-network/paralink-node/tree/master/src/templates). For the next steps we would like to extend it with a simple user management and contract interaction (Solidity, Polkadot) through Metamask.

We do not have any design at the moment (we just use SemanticUI), so it is more of a freestyle job for now. 🙈 
Therefore we would happily accept any help from your side.

**Comment by ZiyedB** [comment]
@jbargu Let me get up to speed ( need to get setup and look more how all repos work together, blockchain environment is new to me ). 
I also don't mind the freestyle ^^". From my understanding it's going to be a simple "backoffice" for users 

If there is any dev docs as well, I'll take it ( saw this one : https://docs.paralink.network/developer-guide/getting-started.html, but feels like it's more for running the nodes etc. )

**Comment by Netherdrake** [comment]
@ZiyedB email us at info@paralink.network, I will invite you to our slack
