### ISSUE TITLE
User model and user creation

### ISSUE THREAD

**Issue by jbargu** [paralink-network/paralink-node#29]
Create a User model with a username and a password hash. On the very first boot (or if the User model is empty) a user is prompted to enter the email for the user and the password. Password has to be confirmed. The user is then saved to the DB and is used to authenticate API endpoints.

**Comment by frisitano** [comment]
I have made a start on this using `bcrypt` to generate the password hash and `sanic-jwt` for endpoint authentication.  There is still some outstanding working required.  You can see the compare against my `network_table` PR #31 [here](https://github.com/frisitano/paralink-node/compare/network_table...frisitano:user_model).

**Comment by jbargu** [comment]
This will require some collaboration with the FE devs, the corresponding UI issue is [here](https://github.com/paralink-network/paralink-ui/issues/7).
