### ISSUE TITLE
plugins.yaml is missing

### ISSUE THREAD

**Issue by Netherdrake** [paralink-network/paralink-node#39]
Host: Ubuntu 20.04
```
~/G/P/paralink-node % docker --version
Docker version 19.03.8, build afacb8b7f0
```

```
paralink-node_paralink_node_1 exited with code 1
paralink_node_1  | Loading .env environment variables...
paralink_node_1  | Traceback (most recent call last):
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/bin/alembic", line 8, in <module>
paralink_node_1  |     sys.exit(main())
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/config.py", line 559, in main
paralink_node_1  |     CommandLine(prog=prog).main(argv=argv)
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/config.py", line 553, in main
paralink_node_1  |     self.run_cmd(cfg, options)
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/config.py", line 530, in run_cmd
paralink_node_1  |     fn(
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/command.py", line 294, in upgrade
paralink_node_1  |     script.run_env()
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/script/base.py", line 481, in run_env
paralink_node_1  |     util.load_python_file(self.dir, "env.py")
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
paralink_node_1  |     module = load_module_py(module_id, path)
paralink_node_1  |   File "/home/worker/.local/share/virtualenvs/node-yFziVaIP/lib/python3.8/site-packages/alembic/util/compat.py", line 182, in load_module_py
paralink_node_1  |     spec.loader.exec_module(module)
paralink_node_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
paralink_node_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
paralink_node_1  |   File "src/migrations/env.py", line 10, in <module>
paralink_node_1  |     from src.config import config as app_config  # noqa: E402
paralink_node_1  |   File "./src/__init__.py", line 13, in <module>
paralink_node_1  |     from src.config import config
paralink_node_1  |   File "./src/config.py", line 41, in <module>
paralink_node_1  |     class Config:
paralink_node_1  |   File "./src/config.py", line 93, in Config
paralink_node_1  |     yaml.safe_dump(plugins_config, open(PLUGINS_CONFIG_PATH.absolute(), "w"))
paralink_node_1  | PermissionError: [Errno 13] Permission denied: '/home/worker/.paralink/plugins.yaml'
paralink_node_1  | Loading .env environment variables...
paralink_node_1  | Traceback (most recent call last):
paralink_node_1  |   File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
paralink_node_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
paralink_node_1  |   File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
paralink_node_1  |     __import__(pkg_name)
paralink_node_1  |   File "/node/src/__init__.py", line 13, in <module>
paralink_node_1  |     from src.config import config
paralink_node_1  |   File "/node/src/config.py", line 41, in <module>
paralink_node_1  |     class Config:
paralink_node_1  |   File "/node/src/config.py", line 93, in Config
paralink_node_1  |     yaml.safe_dump(plugins_config, open(PLUGINS_CONFIG_PATH.absolute(), "w"))
paralink_node_1  | PermissionError: [Errno 13] Permission denied: '/home/worker/.paralink/plugins.yaml'

```

**Comment by frisitano** [comment]
Hmm I'm not experiencing this issue.  It may be that the docker container is having trouble accessing the mount on your machine.  Have you updated the `HOME_MOUNT_DIR` environment variable in [`.env`](https://github.com/paralink-network/paralink-node/blob/master/.env.template) to reflect a pre-existing directory on your local machine?

**Comment by Netherdrake** [comment]
Yes, but it doesn't seem to be taking value from `HOME_MOUNT_DIR`.

**Comment by frisitano** [comment]
The volume mount mapping is specified in [`docker-compose.yml`](https://github.com/paralink-network/paralink-node/blob/master/docker-compose.yml#L15).  The `plugins.yml` is created at the mount path on the first run of the node as seen in [`config.py`](https://github.com/paralink-network/paralink-node/blob/master/src/config.py#L91).  I suspect that the docker container does not have sufficient privileges to create a file on the volume mount.  It may be worth trying to run the `docker-compose` command with `sudo` privileges but in any case this appears to be an environment specific issue.

**Comment by Netherdrake** [comment]
![Screenshot from 2021-02-17 02-53-32](https://user-images.githubusercontent.com/3516903/108145241-63cd4100-70cb-11eb-8423-f7dd301d0431.png)

**Comment by Netherdrake** [comment]
Is this file supposed to be created by the user? Why does it not just load some default plugins if custom config does not exist?

**Comment by frisitano** [comment]
No the user does not need to create the file.  It is created automatically by the node if it doesn't exist at the specified config path.  The files containing the default values are stored in [`src/data`](https://github.com/paralink-network/paralink-node/tree/master/src/data).  I have tested this on my machine and the automated creation of these files works fine for me.

![image](https://user-images.githubusercontent.com/35734660/108180396-9fcdc980-70fe-11eb-8ba9-c641611bdbbb.png)

**Comment by jbargu** [comment]
The problem lies in the `.paralink` folder. I believe you let the `docker-compose` create the folder when mounting (due to `root` user/group on the `.paralink` dir) and then the container has no permissions to create the files - it just happens to be `plugins.yaml` as it is among the first ones to be created.

Remove the `.paralink` with `sudo rm -rf .paralink` and then create the folder yourself with `mkdir .paralink` (as suggested in the README) in the desired `HOME_MOUNT_DIR` folder and see if it works.

**Comment by Netherdrake** [comment]
No, folder permissions were not the issue. 

I found the issue now: if the `HOME_MOUNT_DIR` is anything other than home folder it will break (only ipfs folders get created).

**Comment by jbargu** [comment]
Hmmm, `ipfs` folder is also mounted in `docker-compose` file.

I tried both scenarios, creating a folder `/home/jure/paralink` (a new directory, as in your example) and assign it to `HOME_MOUNT_DIR`. If I do not create `.paralink` folder, I get the same permission error as you, however If I create the folder before running the `docker-compose` it works. I am not sure, could it be something with `uid` and `gid` of the user that you are on?
